### ISSUE TITLE
Allow property overriding when using an entity template

### ISSUE THREAD

**Issue by bleak-and-bare** [acf-patrick/base#34]
> Each component object/field should be immutable and replaced directly by the content of the patch

If we write : 
```yaml
Template:
  Name: mob
  Patch:
    TransformComponent:
      Scale: [2, 2]
```

with a template  :
```yaml
# mob.entt
TransformComponent:
  Position: normalizedWindowCoords(0.5, 0.5)
```

We should get :
```yaml
TransformComponent:
  Scale: [2, 2]
```
